TARGET = usb_usb_debug

#UNIMAP_ENABLE = yes
#KEYMAP_SECTION_ENABLE = yes

# LUFA debug print
# This may prevent USB enumeration and keyboard init
LUFA_DEBUG = yes
# Select one of outputs for debug print
LUFA_DEBUG_UART = yes
#LUFA_DEBUG_SUART = yes

# USB_Host_Shield_2.0 debug print
# This may prevent USB enumeration and keyboard init
#OPT_DEFS += -DDEBUG_USB_HOST

CONSOLE_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
include Makefile
