TARGET = usb_usb_debug

#UNIMAP_ENABLE = yes
#KEYMAP_SECTION_ENABLE = yes

# LUFA debug print
# This may prevent USB enumeration and keyboard init
#TMK_LUFA_DEBUG = yes
# Select one of outputs for debug print
#CONSOLE_DRIVER=UART
#CONSOLE_DRIVER=SUART

# USB_Host_Shield_2.0 debug print
# This may prevent USB enumeration and keyboard init
OPT_DEFS += -DDEBUG_USB_HOST

CONSOLE_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
include Makefile
