# With two interfaces on PS/2 connector
TARGET ?= ibmpc_usb_x2
MCU = atmega32u2
SRC ?=	protocol/ibmpc.cpp \
	ibmpc_usb.cpp

COMMAND_ENABLE ?= no		# Commands for debug and configuration

IBMPC_SECONDARY ?= yes		# enable secondary interface
IBMPC_MOUSE_ENABLE ?= yes	# enable mouse support

include Makefile
